name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions
on:
  push:
    branches:
      - abc
jobs:
  Practice-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: identify user
        run: echo "Hello ${{ github.actor }}"
      
      - name: idk
        run: echo "something"
